### ISSUE TITLE
Allow setting a custom prefix

### ISSUE THREAD

**Issue by rithvikvibhu** [befranz/hshelp#1]
Since the install script is going to be installed on cloud VMs, and the blockchain size keeps increasing, many would prefer storing hsd data on an attached block storage (or whatever the cloud providers call it).

Maybe an optional argument for `--prefix` which defaults to $HOME/.hsd?

**Comment by befranz** [comment]
Great idea and there's already install-all-hsd v1.2.0 which allows an alternative path as parameter.
https://github.com/befranz/hshelp#installation

**Comment by rithvikvibhu** [comment]
Whoa that was fast! Didn't expect it be updated so set it up manually this time. Will use the script from next time, thanks!
