### ISSUE TITLE
verify PGP sigs?

### ISSUE THREAD

**Issue by pinheadmz** [befranz/hshelp#2]
Just a thought, your script could import public PGP keys for me Nodar and chjj and verify the code it downloads from github.

**Comment by befranz** [comment]
Sure! Any hint how to do it best?

**Comment by pinheadmz** [comment]
hint 1: https://github.com/handshake-org/hsd/security/policy

hint 2: `git log --show-signature`

hint 3: 

```
--> git verify-tag v3.0.1
gpg: Signature made Thu Oct 21 10:52:37 2021 EDT
gpg:                using RSA key E61773CD6E01040E2F1BD78CE7E2984B6289C93A
gpg: Good signature from "Matthew Zipkin (GitHub Signing Key) <pinheadmz@gmail.com>" [ultimate]
```

hint 4: https://github.com/braydonf/gpk/blob/5fa41445d3fa81f8a62bbe638c26e4c0e14e79b8/lib/git.js#L143-L160

**Comment by befranz** [comment]
Signature check added with v.1.3.0
